---
- name: Copy systemd service file
  template:
    src: app.service.j2
    dest: /etc/systemd/system/app.service

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Start and enable app service
  systemd:
    name: app
    state: started
    enabled: yes
